server:
  port: 80


eureka:
  client:
    register-with-eureka: true     #向eureka server注册中心注册
    fetch-registry: true        #检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址


spring:
  application:
    name: cloud-config-service
  zipkin:
    base-url: http://localhost:9411   #zipkin端口为9411
  sleuth: # 链路监控 下载jar:http://dl.bintray.com/openzipkin/maven/io/zipkin/java/zipkin-server/2.12.9/
    sampler:
      probability: 1 # 采样率值介于0 - 1 之间，1 表示全部采集，通常是0.5