server:
  port: 84

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #配置Nacos地址
#        server-addr: 192.168.184.131:1111   #配置Nacos地址,该地址为本机linux下的地址
    sentinel:
      transport:
        dashboard: localhost:8080   #配置sentinel地址
        port: 8719    #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口


service-url:
  nacos-user-service: http://nacos-payment-provider

#整合feign
feign:
  sentinel:
    enabled: true
