server:
  port: 8001


eureka:
  client:
    register-with-eureka: true     #向eureka server注册中心注册
    fetch-registry: true        #检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址 
  instance:
    instance-id: paymentHystrix8001  #指定注册进Eureka server的服务名
    prefer-ip-address: true   #当鼠标悬停时，显示ip地址


#  server:
#     enable-self-preservation: false

spring:
  application:
    name: cloud-provider-hystrix-payment
#   eviction-interval-timer-in-ms: 2000