server:
  port: 80


eureka:
  client:
    register-with-eureka: true     #向eureka server注册中心注册
    fetch-registry: true        #检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
  instance:
    instance-id: orderHystrix80

#设置feign客户端超时时间
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的最大时间。默认是 1 秒
  ReadTimeout: 5000
  #建立连接所用的最大时间。
  ConnectionTimeout: 5000

spring:
  application:
    name: cloud-consumer-hystrix-payment